Update CI workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,31 +1,37 @@
 name: CI
-on: 
-  push:
-    branches-ignore: [ master ]
-    paths:
-      - 'Jobgroups/**.yaml'
-  pull_request:
-    paths:
-      - 'Jobgroups/**.yaml'
+on: [push, pull_request]
 jobs:
   static-check:
     runs-on: ubuntu-latest 
+    container:
+      image: docker://registry.opensuse.org/home/syrianidou_sofia/containers/tumbleweed:o3-jobgroups
     steps:
       - name: Git Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
         with:
           fetch-depth: 0
+
       - name: Get Job group changed files
         id: changed-files
         run: |
-          CHANGED_FILES=$(git diff --exit-code --diff-filter="*ACDMRTUX" --name-only origin/master | grep Jobgroups | awk -v d=" " '{s=(NR==1?s:s d)$0}END{print s}')
+          git config --global --add safe.directory '*'
+          CHANGED_FILES=$(git diff --diff-filter="*ACDMRTUX" --name-only origin/master job_groups/ | tr '\n' ' ')
           echo $CHANGED_FILES
           echo "::set-output name=files::${CHANGED_FILES}"
+
       - name: Run yamllint for modified Job group schedules
-        run: |
-          for file in ${{ steps.changed-files.outputs.files }}; do
-            yamllint $file
-          done
+        run: yamllint -f github ${{ steps.changed-files.outputs.files }}
+
+      - name: Check for orphaned yaml files
+        env:
+          APIKEY: "${{ secrets.APIKEY }}"
+          APISECRET: "${{ secrets.APISECRET }}"
+        run: ./tool.py --orphans
+      - name: Run serverside checks
+        env:
+          APIKEY: "${{ secrets.APIKEY }}"
+          APISECRET: "${{ secrets.APISECRET }}"
+        run: ./tool.py --dry-run --push
       - name: Clone os-autoinst-distri-opensuse repository
         uses: actions/checkout@v2
         with:
@@ -37,5 +43,10 @@ jobs:
       - name: Check if YAML_SCHEDULE and YAML_TEST_DATA exist in os-autoinst-distri-opensuse
         run: |
           for file in ${{ steps.changed-files.outputs.files }}; do
-            scripts/verify_file_existence $(grep -oP '(YAML_SCHEDULE|YAML_TEST_DATA):\s\K.*' $file | sort -u | awk "{print \"os-autoinst-distri-opensuse/\" \$0}") 
+            for file_ref in $(grep -oP '(YAML_SCHEDULE|YAML_TEST_DATA):\s\K.*' $file | sort -u | awk "{print \"os-autoinst-distri-opensuse/\" \$0}") ; do
+              if ! test -f "$file_ref" ; then
+                echo "Error: Reference from '${file}' to non existing '%{file_ref}'"
+                exit 1
+              fi
+            done
           done
